### ISSUE TITLE
What tools do you use on a daily basis?

### ISSUE THREAD

**Issue by arthurvr** [coderabbi/ama#1]

**Comment by coderabbi** [comment]
I code on a Windows box, so I use the following frequently, though perhaps not daily:
- PHPStorm
- Babun (babun.github.io)
- SmartGitHG
- MySQL Workbench
- Postman
- Slack
- Flock (heyflock.com)
- HexChat
- MS Outlook
- TweetDeck
- Flux
- Spotify
- Focus@Will
- Screen Hero
